### ISSUE TITLE
inconsistent adjacency results 

### ISSUE THREAD

**Issue by schmert** [ipeaGIT/geobr#162] opened 2020-05-22 14:55 UTC
I don't know if this is a general {sf} vs {sp} issue, or whether it is a result of the particular polygons returned by {geobr}.  

In brief, at least some municipal polygons have (slightly) overlapping interiors, which means that using st_relates() to find polygons that satisfy queen-adjacency doesn't work as expected.

I prepared a semi-self-explanatory example [here](http://bonecave.schmert.net/RJ-adjacency.html).  It's inelegant but may demonstrate the point.

**Comment by rafapereirabr** [comment] 2020-05-22 15:17
Hi Carl.

As a default, `geobr` downloads polygons with simplified borders to improve speed in downloading and data visualization. If  a user wants to use the data for proper spatial analysis and statistics, it is strongly recommend to set the argument `simplified = F` as in

```
munis <-  geobr::read_municipality(code_muni = 'RJ', simplified = F)
```
Please let me know if this solves the issue. Perhaps we need to make this clearer in the documentation. What do you think?

**Comment by schmert** [comment] 2020-05-22 15:25
Thanks. That is news to me.  I do not see that as an available parameter when I look for help on the function. 

Yes, I recommend making that much more prominent somehow. 

![read_municipality_help](https://user-images.githubusercontent.com/6287005/82683362-e6999c00-9c1e-11ea-83ea-e94b4fb3b81c.png)

**Comment by schmert** [comment] 2020-05-22 15:28
In version 1.0,  adding that _simplified_ argument generates an error.  When did this simplified/unsimplified distinction happen?

**Comment by schmert** [comment] 2020-05-22 15:43
Another oddity: updating to version 1.3 changed the results of my experiment even with the default, simplified polygons.  Running that same program with version 1.3 (unlike 1.0) led to identical queen-neighborhoods for Areal with the _st_intersection_ and _poly2nb_ approaches.

**Comment by schmert** [comment] 2020-05-22 16:09
After an update to version 1.3, and now using simplified=FALSE,  the problem persists.  Municipal polygons still have overlapping interiors.  So maybe this is an IBGE problem. 

Second results, with 1.3 and simplified=FALSE,  [here](http://bonecave.schmert.net/RJ-adjacency-unsimplified.html).

**Comment by rafapereirabr** [comment] 2020-05-25 12:59
Hi Carl.  Thanks for such a detailed analysis.

The `simplified` argument was properly introduced in version 1.3. We will be changing the documentation to make this clearer to the user, as you suggested. This will be the explanation to the argument. Let me know if that is clear enough. Ping to @JoaoCarabetta who might need to update the documentation of our `Python` version.

```
#' @param simplified Logic FALSE or TRUE, indicating whether the function returns the
#' data set with 'original' resolution or a data set with 'simplified' borders (Defaults to TRUE).
#' If a user wants to conduct proper spatial analysis and statistics, it is strongly recommend
#' to set the argument simplified = F
```

Regarding the data itself, I have now checked and it looks like the origin of the problem comes from the original data set generated by IBGE. I have run your code on the original data and the the output is the same (see code below). If this is of any help, the Areal neighborhood analysis seems to work fine when using data from 2018. I haven't checked other years, though.

```
RJ = read_municipality(code_muni = 'RJ', simplified = F, year = 2018)
```

### test on original data from IBGE

```
## download original municipality daa for Rio in 2010
# ftp://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_municipais/municipio_2010/rj/

RJ <- sf::st_read('C:/Users/rafa/Desktop/rj_municipios/33MUE250GC_SIR.shp',
                  quiet = T, stringsAsFactors=F, options = "ENCODING=WINDOWS-1252")

names(RJ)[3] <- 'name_muni'

hood = c('AREAL',
         'PARAÍBA DO SUL',
         'PETRÓPOLIS',
         'SÃO JOSÉ DO VALE DO RIO PRETO',
         'TRÊS RIOS'
)

Areal_hood = filter(RJ, name_muni %in% hood)


ggplot(data=Areal_hood) +
  aes(fill=name_muni,label=name_muni) +
  geom_sf() +
  geom_sf_text(size=3) 



st_queen <- function(a, b = a) {
  st_relate(a, b, pattern = "F***T****")
}

# queen-adjacent to Areal)
Areal_adj_list = st_queen(Areal_hood[1,], Areal_hood)
Areal_adj_list
```

**Comment by schmert** [comment] 2020-05-25 15:03
The proposed documentation for the _simplified=_ argument looks good. My only suggestion is to add some description of _how_ the polygons are simplified. What algorithm?

**Comment by rafapereirabr** [comment] 2020-05-25 17:04
Before version 1.2, the only choice was to download the data with original resolution. I've tried to clarify the method below.

#' @param simplified Logic FALSE or TRUE, indicating whether the function returns the
#' data set with 'original' resolution or a data set with 'simplified' borders (Defaults to TRUE).
#' If a user wants to conduct proper spatial analysis and statistics, it is strongly recommend
#' to set the argument simplified = F. Borders have been have been simplified by removing vertices #' of borders using st_simplify{sf} preserving topology with a dTolerance of 100.

**Comment by schmert** [comment] 2020-05-25 17:37
Thanks, Rafa.  That explains several things. My results didn't change when I went from (Version 1.0, default resolution) to (Version 1.3, simplify=FALSE) because the default polygons in version 1.0 were in fact the unsimplified ones. 

One comment about the English that I didn't notice on first reading:  it should be "it is strongly **recommended**", not "it is strongly **recommend**".  In any case I suggest changing the whole sentence to the simpler and more direct "For spatial analysis and statistics users should set _simplified = FALSE_".

**Comment by rafapereirabr** [comment] 2020-05-25 19:05
Thanks for the feedback, Carl!

**Comment by rafapereirabr** [comment] 2020-05-25 19:28
Carl, I don't know if there is a way simple to fix original IBGE polygons to address the inconsistent adjacency issue. I'll leave this issue open for some time, but someone finds a solution. In the mean time, my suggestion is that you use data from more recent years, which have better accuracy in general.

**Comment by rafapereirabr** [comment] 2021-02-13 15:38
Hi Carl. So the problem is really in IBGE's original files, particularly for old years. I'm closing this issue for now, but please feel free to open it again if you find a solution.

**Closed by rafapereirabr** 2021-02-13 15:38 UTC
